### ISSUE TITLE
Make it easy

### ISSUE THREAD

**Issue by dicko2** [agoda-com/dotnet-build-metrics#13]
I'd like the part of our readme about setup to be only

```
install package X
```

No extra steps.

From an OpenSource perspective... It's very important for adoption that its easy to adopt, if you dont make things easy, people wont use your stuff and you project will die.

From an InnerSource perspective... Within a company you can have a central team that "owns" libraries and pushes out PRs and deals with breaking changes, etc. But you need to ask yourself, is it easier to just "make it easy" for other teams to use your stuff (similar to the open source approach) and they wont mind updating the package themselves, "make it easy" and the dependabot updates can be merged without concern.

I think there's a Hungarian term like this that someone told me once where this one came from, but let's just "Make it Easy" :)

**Comment by shane-agoda** [comment]
Closed by PR #14
